### ISSUE TITLE
People.

### ISSUE THREAD

**Issue by mm0hgw** [TheDemocracyFoundation/epitome#126]
I don't think you understand the impact people have on direct democracy.

I was involved in a student occupation governed by direct democracy, and an agent provocateur came into the governance meeting with a camera. This was against the occupation rules, but the agent provocateur refused to comply with the occupation rules. Because he refused to comply with the rules, the occupation meeting adjourned to another room, resolved to relieve the agent provocateur of his footage, and dispatched agents to enforce this ruling.

According to Scots law, the occupation meeting, by making this resolution, conspired to perpetrate theft (a criminal act) against a private citizen. I stood in the way of the execution of this resolution, because while the occupation was unlawful, it was peaceful and not criminal. While it was not criminal, the police had no excuse to enter.

The minutes of the meeting where this illegal resolution was passed were a set of handwritten notes. A singular SQL database is technically not much better. Anyone with administrative access can
1. Edit any resolution to make it criminal, or not criminal.
2. Edit the persons voting for a criminal resolution to make the official record that they are/are not conspirators.

In our story, the agent provocateur got footage of rowdy behaviour, but nothing criminal. Even though he heard that I would not see a criminal resolution enacted (angry and rude is a habit), he did not know what the resolution was, only that Lauri Love (interesting fellow) and I would not stand for its execution.

The Free Hetherington Occupation basically didn't understand, in that moment, that they did not have any power to police the unconsenting, and their attempt to do so was conspiracy to commit theft.

Further, criminal law is so complex that there is a distinct profession of criminal lawyer.

How do you protect your users from each other, agent provocateurs, and police, when you don't know who has enough money to bribe the SQL DB admin to change the resolutions and results?

If anyone has the power to change the resolutions and results, isn't this a dictatorship tool?

**Comment by mm0hgw** [comment]
Basically, you can't stop people from making criminally important decisions. Rude as I may be, the backend needs work, and it needs work all the way to the license.

I knew some of the guys that initiated the Hetherington Occupation from Tabletop RPGs, but I don't know any were present to stop what Lauri and I stopped.

You need to recognise that every vote is potentially a conspiracy to commit a crime that a significant minority (like me & Lauri) want nothing to do with and will fight to prevent.

**Comment by mm0hgw** [comment]
If you make this software as proposed, nothing can stop users using it for criminal acts.

I don't think I'm weird for not wanting to be responsible for such acts,

Rather, i think you're weird for not realising you are responsible.

Effectively, this software is a corporate secretary to any decision made through it.

Yet a corporate secretary plays an important role. A role which cannot be delegated to a machine without pain (over realising who controls the machine).

**Comment by mm0hgw** [comment]
Either you need a second house of qualified lawyers, or to exclude non-lawyers from the first house.

You can't make a machine determine what is legal.

How does your apparatus work, when the users determine to murder someone? (You can't stop them from committing to murder, simply by excluding the word 'murder' from potential resolutions)

If I am not a developer, I am not personally liable for any such death caused.

As developers, are you lawyer enough to guarantee you're not guilty of corporate manslaughter when the users are homicidal?

**Comment by MavropaliasG** [comment]
Hi I hope you are well.

This will be closed as it is not an issue regarding the code of the software.

For discussions regarding the philosophy, implementation of the platform and societal issues that may arise, we have our forum. Feel free to visit it and add your thoughts 

https://groups.google.com/forum/#!forum/democracyfoundation

However I will remind you that although I tried numerous times to explain things to you, you couldn't understand some basic things.

A brief answer to your posts above.

1) Manslaughter? I don't know what world you think you live in or how a software for making decisions can cause manslaughter. Totally in the realm of fantasy. Please keep the discussion real and serious.

2) You are gravelly concerned about liability. Please read section 16 from the [GPL](https://www.gnu.org/licenses/gpl.html) and its interpretation right below. Google it a lot and you will understand the developers are completely safe from any liability.

Please refrain from opening another issue here. You can use the forum I gave you above.
