### ISSUE TITLE
GPL Section 16 doesn't deal with the problem

### ISSUE THREAD

**Issue by mm0hgw** [TheDemocracyFoundation/epitome#127]
Clause 16 of the GPL indemnifies the copyright holder from the user. A decision made by the user, can harm people who are not the user.

The Bhopal disaster was a result of legal decisions, legally made. It harmed people who didn't make the decision.

Corporate manslaughter is a thing, exactly because of this.

Your local bowling club can be exactly as criminally liable, by causing a death, by choosing not to service their minibus.

It's not the driver's fault that the brakes fail, if the driver is not responsible for having the brakes serviced.

Who is responsible for the brakes not being serviced? GPL Section 16? Lol.

**Comment by mm0hgw** [comment]
The "unless required by law" clause in GPL section 16 also f*&%s you, if you're planning to use it to evade legal responsibility for the fallout of decisions made by users.
Effectively, the concept of this software is to act as a corporate secretary at a board meeting, for an eminently scalable size of organisation.

You can't have anonymous voting, because you can't know, in advance, which decisions will kill people.

If you can't show you haven't hidden the criminals, you are a criminal.

**Comment by mm0hgw** [comment]
Criticising the code design, is a code issue.

**Comment by mm0hgw** [comment]
I proposed to protect the users from each other.

By using a centralised database you don't, and let the next Stalin edit the vote counts.

**Comment by mm0hgw** [comment]
Dow's corporate secretary wasn't subject to Indian law, with Dow being a US corporation.

You're offering your corporate secertary software publically, in the hope that people in your own jurisdiction, no matter how stupid, will use it, yet also believing you won't be complicit

**Comment by mm0hgw** [comment]
Legitimately, imagine you're the one and only person in the bowling club that voted *for* servicing the minibus brakes.

You're not responsible for the lethal crash, but how can you prove you're the 1% that voted for?

With an anonymous vote, everyone can claim reasonable doubt, which makes the vote counters the only sure place for blame.

**Comment by mm0hgw** [comment]
GPL Section 16 disavows the responsibility of the decisions made by the Athenian forum *only* to members of the forum.

Their slaves, wives and foes are not users of the forum.

**Comment by mm0hgw** [comment]
The previous answer I got from MavG was that this software is not intended to make decisions with *any* legal consequence.

The problem with that idea is that this software requires hosting. This means even within a SOHO *someone* must be responsible to provide hosting. If one can't make any non-user responsible, only users can provide hosting. 

Even then, if there's no legal consequence for *not* doing so, they can withdraw hosting at any time without legal consequence.

If your software can't be used to make a legally consequential decision to provide hosting to run your software, how do you plan to prevent users making the resultant decisions legally consequential?

The only way is to forbid them from using words in propositions. This is a code issue.

If they can use words, they can plan:
- murder
- negligence leading to corporate manslaughter of a non-user
- renewal of their hosting service

To be effectively useful, the software *must*:
- Be able to construct legally binding decisions.
- Pre-emptively distribute all minutes to all members, which makes anonymous voting impossible.

It's not enough to merely count the votes, one must also ensure every users knows, or at least can know trivially, when each vote was counted and by whom it was cast.

At the grand end, this software needs to be able to run a PLC. democratically. This requires a lawyer to be the corporate secretary.

Effectively, this means the code must support a 2nd house. The only way a single house system *can* work is if the single house has sovereign power.

A petty organisation, like a chess club or a university society, has an upstream organisation that limits the legal decisions that can be made.

i.e. Hiring a contract killer doesn't absolve one of murder. While one may not have done the deed, one made the decision the deed should be done.

Automatically, as devs, you're not responsible for *criminal* decisions made using your software.

To be not responsible for *civil* decisions made using your requires:
- proper record keeping
- a 'secretary' role/group who agrees to assume all civil liability from the users.

Without any 'secretary' to hide behind, you devs could end up legally liable for all hosting by all users.

Maybe you're George Soros, and that wouldn't blip your bank account.

**Comment by mm0hgw** [comment]
Did you miss the fad of Mafia? https://en.m.wikipedia.org/wiki/Mafia_(party_game)

It's a voting game where not everyone is on the same side. Likewise, you shouldn't be assuming your users are all on the same side and able to resolve every dispute without legal recourse.

Understanding who your users are is a code issue.

On the grounds that I once was a dev, you can't even get all the devs pointed in the same direction... On what basis can you assume your users won't disagree to the point of filing legal suit against each other?

Because they shouldn't fool themselves into thinking the results of the software matter? If the devs say the results don't matter, why would anyone ever use the software? What purpose does it have?

The list of people willing to deliberate over decisions, when the results won't matter, is short.

Yet if the results *do* matter, they can have legal consequence to non-users. 

Like the company contracted by the group to provide hosting.

If they have the only copy of the minutes, it gets hard for the group to prove they deliberated anything if the datacentre floods and there are no backups.

Also, with local access and anonymous voting, the hosting company can stuff the ballot in favour of renewing the contract with them.

**Comment by MavropaliasG** [comment]
Hi @mm0hgw,

All those issues your are raising here are valid and important.

However I asked you to refrain from posting those ideas here. This section is only for code issues in the terms of functionality of the code, not the implementation or usage of it. Moreover, writing your ideas here, means that once they are closed, they are going to be lost under a pile of software and bug issues.

I asked you to sue the [google forum](https://groups.google.com/forum/#!forum/democracyfoundation) and although you did post there and I replied, you continue to post here. In that forum, your posts will remain for everyone to see.

I am happy for you to copy and past the new comments you added here to that forum and continue the conversation there. If you want, you can continue the conversation with me on our riot.im private chat as we did, as you will soon find out that I am the only person who will discuss these issues with you in this team. 

I will not close this issue. I will politely ask for you to close it and continue the conversation either on the google group or in the private chatroom with me in riot.im.

Thank you

**Comment by mm0hgw** [comment]
This *is* about functionality of the code.

The code acts as a presiding officer of a democratic forum. This is not a passive function.

Analogously, with a democratic company, where shareholders and board members are the same group, being corporate secretary to such a group is not a passive function.

A court reporter does the same job of recording in writing, the deliberations of a body, but the court reporter is not *complicit* in the decisions made, where they are accurately recorded.

The modern Greek government had to choose between defaulting on debt to the Troika, and cutting benefits to the people. It couldn't choose to pay both, because it can't print money.

When your user groups, who also can't print money, injure third parties by not paying them, can you claim you are not complicit in decision? On what basis?

If the third party is a government, legitimately entitled to tax reciept, and the users choose not to pay, who among them is responsible for *how* the meeting is minuted?

Even the admin responsible for providing hosting can say 'not I,' as can all users.

In my Hetherington days, there was a secretary at all meetings. The secretary both decided who spoke, and recorded the minutes. They had no plausible deniability for any decision made, where they chose to minute.

The software will not understand unreasonable, no matter how deep the bun fight gets. Nor will it understand the ten thousand local jurdictions of the world.

To make this work, the users must not be the people, or even the popular forum, the users must be the proedroi. Only they are willing to *take* legal responsibility to third parties away from the devs.

I guess if there are proedroi, willing to be users, to make democracy possible for their sub-users, this would be a workable model under the GPL.

It's not what you have.

**Comment by MavropaliasG** [comment]
Thank you for your messages. I will close the discussion here since you have posted on the forum. Thank you for posting there. Lets keep the discussion there from now on please.

I do feel its better to have the discussion there so that it may stay visible for the future as well, and not be buried under closed github issues.
