### ISSUE TITLE
Change GMT time to local time in server

### ISSUE THREAD

**Issue by MavropaliasG** [TheDemocracyFoundation/epitome#25]
When creating a new poll and I press "Now" as the time of creation, the time is in GMT not local.

**Comment by MavropaliasG** [comment]
Can we change something here ?

https://github.com/TheDemocracyFoundation/epitome/blob/763ced1b44114bb8ceaf94091f773980af6949fa/Epitome/settings.py#L113

**Comment by TokmakidisP** [comment]
Time zone can be changed to reflect local server time by changing the value TIME_ZONE to a specific one as shown here:
[time zones](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)
