### ISSUE TITLE
Do other browsers need to be inserted here as well ?

### ISSUE THREAD

**Issue by MavropaliasG** [TheDemocracyFoundation/epitome#39]
https://github.com/TheDemocracyFoundation/epitome/blob/baaf073f8a0bf89451044f18c03594db7134e75d/templates/error.html#L7

**Comment by pbout** [comment]
The entire tag can be removed. Nothing I see justifies special treatment for the IE platform, and even if it did compatibility view has been dropped for IE11 and only affects previous deprecated versions. Will be removed.

**Comment by MavropaliasG** [comment]
Other files have this code as well. They can be viewed if one uses the search fuction for the word "chrome"

**Comment by pbout** [comment]
Only those within the static folder which was the older approach(now removed in 0f09b1e). The new templates do not include this.

**Comment by MavropaliasG** [comment]
epitome/templates/home.html contains this. Please perform a thorough search in the repository as suggested.
