### ISSUE TITLE
Should polls be in a separate app  ?

### ISSUE THREAD

**Issue by MavropaliasG** [TheDemocracyFoundation/epitome#43]
Should the polls be in a separate app as @pbout mentioned?

What do you propose as a name ? 

Are "Demoscopisis", or "Demoscopy"/"Demoscope", good names?

**Comment by pbout** [comment]
I personally prefer "Demoscopisis". This however could be a linguistic bias as searching for the word itself produces no results. Demoscope is the prevalent one with demoscopy being second. Using the more popular term of the world could be easier for users to remember but using the unpopular one could stand out better.
I would also prefer polls to be in a separate app as having tasks scattered among apps would hinder development in the long run.

**Comment by MavropaliasG** [comment]
I also prefer "Demoscopisis" as it is in line with the other names we chose for our extensions http://democracy.foundation/roadmap/ . What do you think @TokmakidisP ?

**Comment by MavropaliasG** [comment]
Demoscopesis has been selected
