### ISSUE TITLE
Database name changes could create problems ?

### ISSUE THREAD

**Issue by MavropaliasG** [TheDemocracyFoundation/epitome#46]
https://github.com/TheDemocracyFoundation/epitome/blob/763ced1b44114bb8ceaf94091f773980af6949fa/Eisegesis/templates/Eisegesis/index.html#L70

I have noticed that in commit c6b1c36  the database names changed, for example P_TITLE -> PL_TITLE.

Could there be problems in the views of the static files that call them, for example in Eisegesis/templates/Eisegesis/index.html  as mentioned in this issue ?

**Comment by TokmakidisP** [comment]
It depends. If they are used by their name yes it will cause a problem.

**Comment by MavropaliasG** [comment]
It appears that they did create problems and commit 763ced1 fixes some. Are there some more names that need fixing in the code ?
