### ISSUE TITLE
Do we have representatives?

### ISSUE THREAD

**Issue by mm0hgw** [TheDemocracyFoundation/epitome#47]
Thing have got a bit newspeak with @MavropaliasG.

Apparently epitome doesn't have representatives.

@MavropaliasG seems quite happy to have people appointed to make decisions on behalf of the group where time is a pressing factor. These *de facto* representatives wouldn't actually be representatives because <insert vigorous hand waving>.

Another situation where having representatives is useful is in ratifying formal agreements. Where a group has a formal representative, that representative can sign a document on behalf of the group. Without such a representative, *every* member of the group must sign the document for the group to have signed the document. Why send one man to sign a piece of paper when you can send hundreds?

In recourse to court or arbitration, whether as plaintiff or defendant, the group will have to appoint a representative to make an argument or cede without argument.

Representatives aren't inexorably a problem. Failure to hold representatives to account for their actions is a problem.

**Comment by MavropaliasG** [comment]
As I said in the other post, when I was referring to a representative, I was only giving you an idea to the problem you brought up about an immediate action needing to be taken in a nation. Something that we are not focusing now and certainly not in the immediate future. I just wanted to give you a suggestion how a direct democracy system would work in a nation in general. Epitome’s focus is not on national governance at the moment and will certainly do not involve representatives.

The way to act upon the decisions will be different between each group. We do not focus on how each group decides to enforce/act each decision taken. We care about create a robust method to create those decisions. But if we get a good idea for an extension that will enrich not only the process of creating agreement but also enforcing it, we will be happy to include it as an option.

Having a representative sign a document in behalf of a group based on the consensus generated by the group is a good idea, however the group must have previously agreed on that. What we care is to provide a methods that will not rely on any representation/intermediates for the whole process of decision making, decision enforcing is up to each group.

However, I really like that we are discussing the enforcement of decisions/contracts, as that will definitely enrich the platform in the future, in case we developed subsystems that can be used for that.

**Comment by mm0hgw** [comment]
So no representatives? You'd rather this project was meaningless than used representatives?

**Comment by MavropaliasG** [comment]
I can see this conversation seems to have more to it. However it will be best discussed in our discussion group and not as a software issue in github. We have a discussion group that will be of interest to other users as a future reference. In fact, I regret I didn't do that earlier as all this conversation will be lost in the closed issues of github. Please open a new topic here so it will remain in the website and future users can join http://democracy.foundation/discussion-group/
