### ISSUE TITLE
Who is epitome for?

### ISSUE THREAD

**Issue by mm0hgw** [TheDemocracyFoundation/epitome#48]
@MavropaliasG says epitome should be both for those who want to use a collective decision making tool as a method to make legally enforceable decisions the collective has agreed to abide by in advance, and legally unenforceable decisions the collective has not agreed to abide by.

At the beginning of a football game, the referee tosses a coin to decide which team kicks off the first half. The decision made by coin is legally enforceable, and both teams agree in advance to abide by the decision.

If the teams did not agree to abide by the decision of the coin flip, what would be the point in flipping the coin?

Exactly the same as the point in using epitome to make a decision that nobody has agreed in advance to abide by.

What is the point in expending effort to make a decision if you have no intention for anyone to abide by that decision?

For what can a group use epitome (a decision-making tool), if they have exercised the option not to use it to make decisions?

**Comment by mm0hgw** [comment]
@MavropaliasG sketched an example where the rest of us resolved he should pay each of us 150 dollars, and claimed this was legally unenforceable.

If epitome is a functional decision making tool, it must record decisions. If the decision is recorded, it is legally enforceable if @MavropaliasG agrees it is.

There would be no point at all in resolving @MavropaliasG should hand over money if he has not agreed to abide by the resolution.

So, for us to resolve @MavropaliasG should hand over money, and the rest of us not to be as dumb as a bucket of hair, @MavropaliasG must have agreed to abide by the resolutions of the collective.

@MavropaliasG could notify the group at any point that he is going to cease abiding by the resolutions of the group. If he did this before the resolution compelling him to hand over money, there would be no point in making the resolution. If he did it afterwards, the resolution would still apply because @MavropaliasG at the time the agreement was still in effect, epitome would have record of both this and of @MavropaliasG having rescinded this agreement to abide by resolutions only after the resolution assigning civil liability to him had passed.

**Comment by MavropaliasG** [comment]
I can see this conversation seems to have more to it. However it will be best discussed in our discussion group and not as a software issue in github. We have a discussion group that will be of interest to other users as a future reference. In fact, I regret I didn't do that earlier as all this conversation will be lost in the closed issues of github. Please open a new topic here so it will remain in the website and future users can join http://democracy.foundation/discussion-group/
