### ISSUE TITLE
Why do you want to *discuss* representatives?

### ISSUE THREAD

**Issue by mm0hgw** [TheDemocracyFoundation/epitome#51]
Why do you think there is a discussion to be had?

Either:

- you want to give your users all the options, including the option to have representatives, 

or 

- you wish to forbid users from having representatives and don't wish to give them all the options.

You need to dump one of these design specs since they're fundamentally incompatible.

Discussion, in any quantity, won't change this.

**Comment by MavropaliasG** [comment]
I do want to give our users all the options, including the option to have representatives. Closing as irrelevant to the software. Please refer to the discussion group for discussions that are not code related  http://democracy.foundation/discussion-group/. Thank you

**Comment by MavropaliasG** [comment]
I do want to give our users all the options, including the option to have representatives. Closing as irrelevant to the software. Please refer to the discussion group for discussions that are not code related  http://democracy.foundation/discussion-group/. Thank you

**Comment by mm0hgw** [comment]
You're claiming the design specification of the code is not related to the code?
