### ISSUE TITLE
Contribution/contracts system

### ISSUE THREAD

**Issue by Venryx** [TheDemocracyFoundation/epitome#59]
I saw the CONTRACTS.md file.

I suggest that you keep this system, except use a platform specifically designed for this purpose. The best one I know of is BountySource: https://www.bountysource.com/

Here is their FAQ: https://github.com/bountysource/core/wiki/Frequently-Asked-Questions

**Comment by MavropaliasG** [comment]
@Venryx thank you much for the suggestion Stephen and for the work you're doing on Debate Map!

I'll definitely take a look at it. I will leave this open so I will keep it mind when the time comes and we indeed get a contract out, probably not soon but one day we'll need to. Thanks :)
